# App का नाम
spring.application.name=myapps

# Server port (default 8080)
# Port (Render अपनी port देगा)
server.port=${PORT:8080}
# spring.thymeleaf.cache=false
spring.thymeleaf.cache=true

# Logging level
logging.level.root=INFO
logging.level.com.example.myapps=DEBUG

# H2 Database (in-memory)
# spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.url=jdbc:h2:file:./data/studentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (browser से database देखने के लिए)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# रिमोट कनेक्शन की अनुमति दें
spring.h2.console.settings.web-allow-others=true